# **Ejercicio NÂ° 1:**

In [30]:
import pandas as pd #importamos pandas para usar dataframe
import numpy as np #importamos numpy para usar matrices
from datetime import datetime, timedelta

# Establecer la semilla para reproducibilidad
np.random.seed(0)

# con esto establecememos la variable "hoy" con la fecha de  hoy
hoy = datetime.today()

#con estos estableces una serie con los ultimos 5 dias a partir de hoy la cual la usaremos para los indices del dataframe
fechas = [hoy - timedelta(days=i) for i in range(5)]

fechas.reverse()  # Ordenamos los dias cronlogicamente

# Convertimos las fechas en strig
fechas_str = [fecha.strftime("%Y-%m-%d") for fecha in fechas]

# Crear un DataFrame con datos aleatorios
df1 = pd.DataFrame(
    data=np.random.randint(1, 20, (5,1 )),  # valores entre 0 y 20, en 5 filas y 1 columna
    columns=["NumeroUnid"],  # agregamos (temporalmente solo una columna llamada "NumeroUnid"
    index=fechas_str
)

# agregamos una columna llamada "Produc" con los valores:"Bolsos","Zapatos","Camisas","Enaguas","Sombreros"]
df1["Produc"] = ["Bolsos", "Zapatos", "Camisas", "Enaguas", "Sombreros"]

# agregamos una columna llamada PrecioUni la cual seran valores aleatorios que van del 1 al 100 redondeados en 2 decimales
df1["PrecioUni"] = np.round(np.random.uniform(1, 100, size=5), 2)

# agregamos una columna llamada TotalSinDesc la cual es una multiplicacion de la columna NumeroUnid por PrecioUni
df1["TotalSinDesc"] = df1["NumeroUnid"] * df1["PrecioUni"]

# agregamos una columna llamada TotalConDesc para mostras el precio ya rebajando el 5%
df1["TotalConDesc"] = np.round(df1["TotalSinDesc"] * 0.95, 2)

# Reordenamos las columnas para que se vean mejor
columnas = ["Produc", "NumeroUnid", "PrecioUni", "TotalSinDesc", "TotalConDesc"]
df1 = df1[columnas]


# Mostrar el DataFrame
df1

               Produc  NumeroUnid  PrecioUni  TotalSinDesc  TotalConDesc
2024-06-07     Bolsos          13      84.88       1103.44       1048.27
2024-06-08    Zapatos          16      62.73       1003.68        953.50
2024-06-09    Camisas           1      39.05         39.05         37.10
2024-06-10    Enaguas           4      30.46        121.84        115.75
2024-06-11  Sombreros           4       6.61         26.44         25.12

# **Ejercicio NÂ° 2**

In [31]:
import pandas as pd #importamos pandas para crear series

# Diccionario con los Supuestos Ingresos
ingresos = {
    "Bill Gates": 10000, "Mark Twain": 8000, "Elon Musk": 9500, "Ada Lovelace": 7500, "Marie Curie": 8200,
    "Leonardo da Vinci": 8700, "Steve Jobs": 9200, "Albert Einstein": 8800, "Grace Hopper": 7800, "Nikola Tesla": 9100,
    "Jane Austen": 7200, "Isaac Newton": 9300, "Coco Chanel": 8400, "Michael Jordan": 8900, "Amelia Earhart": 8600
}

# Crear la serie Singressos partir del diccionario de ingresos
serie_ingresos = pd.Series(ingresos)

# Calculamos el ingreso mÃ­nimo, mÃ¡ximo y media
minimo = serie_ingresos.min()
maximo = serie_ingresos.max()
media = serie_ingresos.mean()

# Creamos otra serie con los datos estadÃ­sticos
estadisticas = pd.Series({'MÃ­nimo': minimo, 'MÃ¡ximo': maximo, 'Media': media})

# Mostramos un encabezado
print("Estadisticas de Ingresos:")

# Mostramos la serie "estadisticas"con los datos redondeados
print(np.round(estadisticas),2);

Estadisticas de Ingresos:
MÃ­nimo     7200.0
MÃ¡ximo    10000.0
Media      8613.0
dtype: float64 2

# **Ejercicio NÂ° 3**

In [33]:
import pandas as pd #importamos pandas para usar dataframe

# Crear el diccionario con los datos
data = {
    'Mes': ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo'],
    'Ventas': [30500, 35600, 28300, 33900, 42500],
    'Gastos': [22000, 23450, 18100, 35700, 32450]
}

# Crear el DataFrame en base al diccionario "data"
df = pd.DataFrame(data)

#agregamos la columna 1 Gasto/Ventas*100
df["Columna 1"] = df["Gastos"] / df["Ventas"] * 100

#agregamos la columna 2 Si Ventas>= 30000, imprimir âMeta Superadaâ, caso contrario imprimir âMeta no Superadaâ.
df['Columna 2'] = ['Meta Superada' if ventas >= 30000 else 'Meta no Superada' for ventas in df['Ventas']]

#agregamos la columna 2 Si Gasto>Ventas, calcular el sobre gasto.
df['Columna 3'] = df.apply(lambda row: row['Gastos'] - row['Ventas'] if row['Gastos'] > row['Ventas'] else 0, axis=1)

# Ventas de los ultimos 3 meses
ventas_ultimos_3_meses = df.loc[2:4, 'Ventas'].sum()

# Gastos de febrero a abril
total_gastos_feb_abr = df.loc[1:3, 'Gastos'].sum()

# Mostramos los totales
print("Total de ventas de los Ãºltimos 3 meses:", ventas_ultimos_3_meses)
print("Total de gastos de febrero a abril:", total_gastos_feb_abr)
print(" ")

print("DataFrame con nuevas columnas:")

df

Total de ventas de los Ãºltimos 3 meses: 104700
Total de gastos de febrero a abril: 77250

DataFrame con nuevas columnas:

       Mes  Ventas  Gastos   Columna 1         Columna 2  Columna 3
0    Enero   30500   22000   72.131148     Meta Superada          0
1  Febrero   35600   23450   65.870787     Meta Superada          0
2    Marzo   28300   18100   63.957597  Meta no Superada          0
3    Abril   33900   35700  105.309735     Meta Superada       1800
4     Mayo   42500   32450   76.352941     Meta Superada          0

# **Ejercicio No 4**

In [40]:
import pandas as pd

# generamos en dataframe desde el archivo "datos_seguros.csv"
#le decimos a python que el separador es punto y coma
#y que el encabezado esta en la primera fila
df = pd.read_csv("datos_seguros.csv", sep=';', header=0)

In [43]:
#Mostramos las Dimensiones del DataFrame:
df.shape

(45798, 17)

In [44]:
#Mostramos el numero total de datos:
df.size

778566

In [45]:
#Mostramos los nombre de las columnas
df.columns.tolist()

['MES_T0',
 'VENTA_SEGURO',
 'NUM_TC_TOTAL_T2',
 'SALDO_BCO_T2',
 'LINEA_BCO_T2',
 'USO_LINEA_BCO_T2',
 'Nro_CTa_Ahorro_Bco_T1',
 'Ahorro_Sldo_Bco_T1',
 'monto_ope_t2',
 'PROM_ANUAL_MTO_OPERA',
 'MAX_MTO_OPERA_Anual',
 'Ratio_HospvsMtoTotal_t2',
 'SEXO',
 'ANTIGUEDAD_MES',
 'DEPARTAMENTO',
 'SOW_BCO_T2',
 'SOW_BCO_SEMESTRAL']

In [46]:
#Mostramos los nombre de las filas
df.index.tolist()

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 ...]

In [47]:
#Mostramos los tipos de datos
df.dtypes

MES_T0                       int64
VENTA_SEGURO                 int64
NUM_TC_TOTAL_T2            float64
SALDO_BCO_T2               float64
LINEA_BCO_T2               float64
USO_LINEA_BCO_T2           float64
Nro_CTa_Ahorro_Bco_T1      float64
Ahorro_Sldo_Bco_T1         float64
monto_ope_t2               float64
PROM_ANUAL_MTO_OPERA       float64
MAX_MTO_OPERA_Anual        float64
Ratio_HospvsMtoTotal_t2    float64
SEXO                        object
ANTIGUEDAD_MES               int64
DEPARTAMENTO                object
SOW_BCO_T2                 float64
SOW_BCO_SEMESTRAL          float64
dtype: object

In [48]:
#Mostramos las 10 primeras filas
df.head(10)

,MES_T0,VENTA_SEGURO,NUM_TC_TOTAL_T2,SALDO_BCO_T2,LINEA_BCO_T2,USO_LINEA_BCO_T2,Nro_CTa_Ahorro_Bco_T1,Ahorro_Sldo_Bco_T1,monto_ope_t2,PROM_ANUAL_MTO_OPERA,MAX_MTO_OPERA_Anual,Ratio_HospvsMtoTotal_t2,SEXO,ANTIGUEDAD_MES,DEPARTAMENTO,SOW_BCO_T2,SOW_BCO_SEMESTRAL
0,201506,0,3.0,0.0,2300.0,0.000000,0.0,0.0,15.00,18.644444,52.80,NaN,M,58,LIMA,0.000000,0.000000
1,201506,0,2.0,3215.0,3500.0,0.918571,0.0,0.0,548.98,2632.020000,5709.24,NaN,M,69,JUNIN,0.816134,0.930867
2,201506,0,1.0,3169.0,5000.0,0.633800,0.0,0.0,0.00,4999.000000,4999.00,0.0,M,16,CALLAO,1.000000,1.000000
3,201506,1,1.0,6495.0,8450.0,0.768639,2.0,505.0,2137.94,4900.191666,11206.80,NaN,F,62,LIMA,0.413831,0.505504
4,201506,0,NaN,NaN,NaN,NaN,0.0,0.0,12.37,12.370000,12.37,NaN,F,5,AREQUIPA,0.000000,0.000000
5,201506,0,3.0,2373.0,9373.0,0.253174,0.0,0.0,411.86,1410.662727,5055.62,NaN,M,44,CALLAO,0.181633,0.677393
6,201506,0,2.0,0.0,0.0,0.000000,1.0,2662.0,46.00,218.393333,390.90,NaN,M,4,LIMA,0.000000,0.000000
7,201506,0,1.0,3023.0,16720.0,0.180801,0.0,0.0,2982.90,1721.769166,3137.70,0.0,M,136,LIMA,1.000000,1.000000
8,201506,0,1.0,1931.0,12500.0,0.154480,0.0,0.0,412.00,986.337500,2119.00,NaN,M,292,LIMA,0.278603,0.541839
9,201506,0,NaN,NaN,NaN,NaN,2.0,40718.0,1644.30,1581.335000,3565.14,NaN,F,49,AREQUIPA,0.000000,0.000000

In [49]:
#Mostramos las 10 ultimas filas
df.tail(10)

,MES_T0,VENTA_SEGURO,NUM_TC_TOTAL_T2,SALDO_BCO_T2,LINEA_BCO_T2,USO_LINEA_BCO_T2,Nro_CTa_Ahorro_Bco_T1,Ahorro_Sldo_Bco_T1,monto_ope_t2,PROM_ANUAL_MTO_OPERA,MAX_MTO_OPERA_Anual,Ratio_HospvsMtoTotal_t2,SEXO,ANTIGUEDAD_MES,DEPARTAMENTO,SOW_BCO_T2,SOW_BCO_SEMESTRAL
45788,201505,0,4.0,0.0,0.0,0.0,0.0,0.0,1054.41,688.975000,1054.41,NaN,F,105,LIMA,0.0,0.0
45789,201505,0,1.0,0.0,0.0,0.0,2.0,8217.0,0.00,681.600000,1337.00,0.0,M,31,ANCASH,0.0,0.0
45790,201505,0,2.0,0.0,0.0,0.0,0.0,0.0,810.00,810.000000,810.00,NaN,M,226,LIMA,0.0,0.0
45791,201506,0,1.0,0.0,0.0,0.0,2.0,9261.0,4244.19,3466.162500,15419.30,0.0,F,204,UCAYALI,0.0,0.0
45792,201505,0,2.0,0.0,12000.0,0.0,2.0,804.0,277.20,237.600000,277.20,NaN,M,8,LA LIBERTAD,0.0,0.0
45793,201505,0,2.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,F,4,LIMA,0.0,0.0
45794,201505,0,NaN,NaN,NaN,NaN,2.0,6189.0,1314.10,1314.100000,1314.10,NaN,F,76,LA LIBERTAD,0.0,0.0
45795,201506,0,NaN,NaN,NaN,NaN,1.0,138.0,36.00,73.114285,220.00,NaN,F,20,LIMA,0.0,0.0
45796,201506,0,NaN,NaN,NaN,NaN,0.0,0.0,0.00,299.468750,830.00,0.0,M,23,PIURA,0.0,0.0
45797,201506,0,1.0,0.0,0.0,0.0,6.0,2762.0,0.00,780.000000,780.00,0.0,M,125,PASCO,0.0,0.0

In [50]:
#datos nulos
df.isnull().sum()

MES_T0                         0
VENTA_SEGURO                   0
NUM_TC_TOTAL_T2            20401
SALDO_BCO_T2               20346
LINEA_BCO_T2               20346
USO_LINEA_BCO_T2           20346
Nro_CTa_Ahorro_Bco_T1       1393
Ahorro_Sldo_Bco_T1          1393
monto_ope_t2               12871
PROM_ANUAL_MTO_OPERA       12871
MAX_MTO_OPERA_Anual        12871
Ratio_HospvsMtoTotal_t2    16079
SEXO                           0
ANTIGUEDAD_MES                 0
DEPARTAMENTO                   0
SOW_BCO_T2                     0
SOW_BCO_SEMESTRAL              0
dtype: int64

In [51]:
#Extraemos las 1000 primeras filas y las almacenamos
primeras_1000_filas = df.head(1000)

In [52]:
#Mostramos el contenerdor con as 1000 ultimas filas
primeras_1000_filas

,MES_T0,VENTA_SEGURO,NUM_TC_TOTAL_T2,SALDO_BCO_T2,LINEA_BCO_T2,USO_LINEA_BCO_T2,Nro_CTa_Ahorro_Bco_T1,Ahorro_Sldo_Bco_T1,monto_ope_t2,PROM_ANUAL_MTO_OPERA,MAX_MTO_OPERA_Anual,Ratio_HospvsMtoTotal_t2,SEXO,ANTIGUEDAD_MES,DEPARTAMENTO,SOW_BCO_T2,SOW_BCO_SEMESTRAL
0,201506,0,3.0,0.0,2300.0,0.000000,0.0,0.0,15.00,18.644444,52.80,NaN,M,58,LIMA,0.000000,0.000000
1,201506,0,2.0,3215.0,3500.0,0.918571,0.0,0.0,548.98,2632.020000,5709.24,NaN,M,69,JUNIN,0.816134,0.930867
2,201506,0,1.0,3169.0,5000.0,0.633800,0.0,0.0,0.00,4999.000000,4999.00,0.000000,M,16,CALLAO,1.000000,1.000000
3,201506,1,1.0,6495.0,8450.0,0.768639,2.0,505.0,2137.94,4900.191666,11206.80,NaN,F,62,LIMA,0.413831,0.505504
4,201506,0,NaN,NaN,NaN,NaN,0.0,0.0,12.37,12.370000,12.37,NaN,F,5,AREQUIPA,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,201506,0,1.0,4357.0,4600.0,0.947173,0.0,0.0,187.58,758.380833,1326.14,NaN,M,25,LIMA,0.194025,0.180906
996,201506,0,NaN,NaN,NaN,NaN,1.0,545.0,104.00,104.000000,104.00,1.000000,F,55,CUSCO,0.000000,0.000000
997,201506,0,NaN,NaN,NaN,NaN,0.0,0.0,414.64,243.107500,550.00,NaN,F,24,LIMA,1.000000,1.000000
998,201506,0,1.0,0.0,0.0,0.000000,0.0,0.0,NaN,NaN,NaN,0.000000,M,50,AREQUIPA,0.000000,0.000000
999,201506,0,4.0,0.0,0.0,0.000000,2.0,436.0,108.52,166.578333,626.52,0.202727,M,94,LA LIBERTAD,0.000000,0.000000